# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-06 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='id',
        ),
        migrations.AlterField(
            model_name='talk',
            name='talk_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
